package Exception;

import java.io.IOException;
import java.nio.file.Paths;
import java.util.Scanner;

public class RunMain {
//    public static void main(String[] args) {
//        int a = 1;
//        int b = 0;
//        try {
//            int c = a / b;
//        } catch (ArithmeticException e) {
//            System.out.println(e.getMessage());
//        } finally {
//            System.out.println("Error kiểu gì thì vẫn chạy");
//        }
//        //System.out.println(a / b);
//        System.out.println("Hello world!!");
//    }

//    public static void main(String[] args) {
//        try {
//            Scanner scanner = new Scanner(Paths.get("demo.txt"));
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
//    }




//    public static void DivisionByZero() throws ArithmeticException{
//        try{
//            System.out.println(1/0);
//        } catch (Exception e){
//            System.out.println(e.getMessage());
//        }
//    }
//    public static void main(String[] args) throws ArithmeticException{
//        DivisionByZero();
//        int arr[] = new int[4];
//        System.out.println(arr[5]); // Số phần tử ngoài phạm vi
//    }





}
